const BACKEND = "https://flip-backend.matveyverus9.workers.dev";
const SUPPORT = "flip_support1";
const state = {
  history: JSON.parse(localStorage.getItem("flipHistory") || "[]"),
  settings: JSON.parse(localStorage.getItem("flipSettings") || '{"notifications":true,"dark":true,"motion":true}'),
  pro: false,
  proUntil: null,
  currentUser: null
};
const $ = id => document.getElementById(id);
const tg = window.Telegram?.WebApp;

function save(){localStorage.setItem("flipHistory",JSON.stringify(state.history.slice(0,30)));localStorage.setItem("flipSettings",JSON.stringify(state.settings));}
function toast(msg){const el=$("toast"),tx=$("toastText");if(!el)return;tx.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2200)}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===id && b.classList.contains("nav-item")));window.scrollTo({top:0,behavior:state.settings.motion?"smooth":"auto"});if(id==="history")renderHistory();if(id==="home")renderRecent()}
function telegramOpen(url){if(tg?.openTelegramLink) tg.openTelegramLink(url); else window.open(url,"_blank")}
function user(){return tg?.initDataUnsafe?.user || null}
function initTelegram(){if(!tg)return;tg.ready();tg.expand();if(tg.setHeaderColor)tg.setHeaderColor("#070a0f");if(tg.setBackgroundColor)tg.setBackgroundColor("#070a0f")}
function setUser(){const u=user();state.currentUser=u;if(!u)return;const name=u.first_name||"друг";$("helloName").textContent=name;$("profileName").textContent=[u.first_name,u.last_name].filter(Boolean).join(" ")||"Пользователь Telegram";$("profileUsername").textContent=u.username?"@"+u.username:"Telegram-профиль";$("profileId").textContent="ID: "+u.id;const big=$("profileAvatar");if(u.photo_url)big.innerHTML=`<img src="${escapeAttr(u.photo_url)}" alt="">`;const mini=$("menuProfileMini");if(mini)mini.innerHTML=`<div class="menu-avatar">${u.photo_url?`<img src="${escapeAttr(u.photo_url)}" alt="">`:`<span>F</span>`}</div><div><b>${escapeHtml([u.first_name,u.last_name].filter(Boolean).join(" ")||"Пользователь Telegram")}</b><small>${u.username?"@"+escapeHtml(u.username):"Telegram-профиль"}</small></div><span class="plan-pill" id="menuPlan">FREE</span>`;}
function escapeAttr(s){return String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

async function health(){try{const r=await fetch(BACKEND+"/api/health",{cache:"no-store"});const d=await r.json();const ok=!!d?.ok;$("backendStatus").textContent=ok?"онлайн":"недоступен";$("backendStatus").className=ok?"online":"offline";return ok}catch(e){$("backendStatus").textContent="недоступен";$("backendStatus").className="offline";return false}}
async function profile(){const init=tg?.initData||"";if(!init)return;try{const r=await fetch(BACKEND+"/api/profile",{headers:{"X-Flip-Init-Data":init},cache:"no-store"});if(!r.ok)return;const d=await r.json();if(!d.ok)return;state.pro=d.plan==="pro";state.proUntil=d.pro_until||null;updateProUI()}catch(e){}}
function updateProUI(){const plan=$("profilePlan"),status=$("proStatus");if(plan)plan.textContent=state.pro?"PRO":"FREE";if(status)status.textContent=state.pro?(state.proUntil?`Pro активен до ${new Date(state.proUntil).toLocaleDateString("ru-RU")}`:"Pro активен постоянно"):"199 ⭐ / 30 дней · оплата через Telegram";const btn=$("buyPro");if(btn)btn.textContent=state.pro?"Pro уже подключён ✓":"Подключить Pro";const hint=$("profileProHint");if(hint)hint.textContent=state.pro?(state.proUntil?"до "+new Date(state.proUntil).toLocaleDateString("ru-RU"):"активен"):"→";const mp=$("menuPlan");if(mp)mp.textContent=state.pro?"PRO":"FREE";}

async function checkKufar(url){const r=await fetch(BACKEND+"/api/listing?url="+encodeURIComponent(url),{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не удалось проверить объявление");return d}
function cleanKufarTitle(raw){let t=String(raw||"").replace(/\s+/g," ").trim();t=t.replace(/,?\s*цена\s+.*$/i,"");t=t.replace(/\s+-\s+купить.*$/i,"");return t||"Объявление Kufar"}
function cleanLocation(raw){let t=String(raw||"").replace(/\s+/g," ").trim();const m=t.match(/в\s+([А-ЯЁа-яёA-Za-z-]+)(?:\s+на Куфаре)?/i);if(m)return m[1];if(/Минске/i.test(t))return"Минск";return t||"Не указано"}
function priceRange(list){const a=(Array.isArray(list)?list:[]).map(Number).filter(Number.isFinite);if(!a.length)return null;return {min:Math.min(...a),max:Math.max(...a),count:a.length}}
function money(n){return Number.isFinite(Number(n))?Number(n).toLocaleString("ru-RU",{maximumFractionDigits:2}):"—"}
function renderBuyResult(d,url){const p=d.data||d;const title=cleanKufarTitle(p.product||p.title);const price=Number(p.price||0);const market=Number(p.market||p.marketAverage||0);const score=Number(p.priceScore||p.score||0);const seller=p.seller&&p.seller!=="Не найден"?p.seller:"Не получен";const location=cleanLocation(p.location);const condition=p.condition||"Не указано";const risk=p.risk||"Проверь товар перед покупкой";const range=priceRange(p.similarPrices);const diff=price&&market?((price-market)/market*100):0;const delta=price&&market?Math.round(Math.abs(diff)*10)/10:null;const marketText=range?`${money(range.min)}–${money(range.max)} BYN`:market?money(market)+" BYN":"—";const scoreText=score?score+"/100":"—";$("buyResult").classList.remove("hidden");$("buyResult").innerHTML=`<div class="result-top"><div><div class="eyebrow">ЧТО ПРОЧИТАЛ FLIP</div><div class="result-title">${escapeHtml(title)}</div><div class="result-price">${price?money(price)+" BYN":"Цена не найдена"}</div><div class="result-meta">${escapeHtml(location)} · ${escapeHtml(condition)}</div></div><div class="score"><small>FLIP</small><b>${scoreText}</b></div></div><div class="result-grid"><div class="metric"><small>Цена объявления</small><b>${price?money(price)+" BYN":"—"}</b></div><div class="metric"><small>Средняя цена</small><b>${market?money(market)+" BYN":"—"}</b></div><div class="metric"><small>Рынок</small><b>${marketText}</b></div><div class="metric"><small>Отклонение</small><b>${delta!==null?(diff<0?"−":"+")+delta+"%":"—"}</b></div><div class="metric"><small>Состояние</small><b>${escapeHtml(condition)}</b></div><div class="metric"><small>Продавец</small><b>${escapeHtml(seller)}</b></div></div><div class="read-block"><div class="read-head"><b>Что удалось определить</b><span>${range?range.count+" похожих цен":"данные источника"}</span></div><div class="read-list"><div><span>✓</span> Цена объявления — ${price?money(price)+" BYN":"не найдена"}</div><div><span>✓</span> Состояние — ${escapeHtml(condition)}</div><div><span>✓</span> Рыночный ориентир — ${market?"около "+money(market)+" BYN":"нет данных"}</div><div><span>${seller==="Не получен"?"!":"✓"}</span> Продавец — ${seller==="Не получен"?"имя не вернулось из источника":escapeHtml(seller)}</div></div></div><div class="risk">⚠️ ${escapeHtml(risk)}</div><a class="result-link" href="${escapeAttr(url)}" target="_blank" rel="noopener">Открыть объявление на Kufar ↗</a>`}
function addHistory(d,url){const p=d.data||d;state.history.unshift({title:p.product||p.title||"Объявление",price:Number(p.price||0),market:Number(p.market||p.marketAverage||0),score:Number(p.priceScore||p.score||0),url,time:new Date().toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})});state.history=state.history.slice(0,30);save();renderRecent()}
function renderRecent(){const box=$("homeRecent");const x=state.history[0];if(!x){box.innerHTML="";return}box.innerHTML=`<div class="section-row small-row"><div><span class="eyebrow">ПОСЛЕДНЯЯ ПРОВЕРКА</span><h3>${escapeHtml(x.title)}</h3></div></div><button class="wide-link" data-open-history="0"><span>⌕</span><div><b>${x.price?x.price+" BYN":"Цена —"} · оценка ${x.score||"—"}</b><small>${escapeHtml(x.time)}</small></div><i>→</i></button>`}
function renderHistory(){const box=$("historyList");if(!state.history.length){box.innerHTML='<div class="empty">История пока пустая.<br>Сделай первую проверку Kufar.</div>';return}box.innerHTML=state.history.map((x,i)=>`<button class="history-item" data-open-history="${i}"><b>${escapeHtml(x.title)}</b><small>${x.price?x.price+" BYN":"Цена —"} · оценка ${x.score||"—"} · ${escapeHtml(x.time)}</small></button>`).join("")}

async function runBuy(){const input=$("buyUrl"),url=input.value.trim();if(!url){toast("Вставь ссылку на объявление");return}if(!/kufar\.by/i.test(url)){toast("Сейчас FLIP проверяет ссылки Kufar");return}const btn=$("runBuy");btn.disabled=true;btn.textContent="Проверяем…";$("buyResult").classList.add("hidden");try{const d=await checkKufar(url);renderBuyResult(d,url);addHistory(d,url);toast("Готово — объявление проверено")}catch(e){$("buyResult").classList.remove("hidden");$("buyResult").innerHTML=`<div class="result-title">Не получилось проверить</div><p class="result-meta">${escapeHtml(e.message||"Ошибка сервера")}</p><button class="secondary" onclick="document.getElementById('buyResult').classList.add('hidden')">Закрыть</button>`;toast("Проверка не удалась")}finally{btn.disabled=false;btn.textContent="Проверить"}}

function makeListing(){const title=$("sellTitle").value.trim()||"Товар";const price=$("sellPrice").value.trim();const cond=$("sellCondition").value;const details=$("sellDetails").value.trim();const text=`${title}\n\nСостояние: ${cond}.${price?`\nЦена: ${price} BYN`:""}${details?`\n\n${details}`:""}\n\nПишите в сообщения — отвечу на вопросы и договоримся о встрече.`;$("listingOutput").classList.remove("hidden");$("listingOutput").innerHTML=`<div class="eyebrow">ГОТОВОЕ ОБЪЯВЛЕНИЕ</div><div style="white-space:pre-line;font-size:13px;line-height:1.55;margin-top:8px">${escapeHtml(text)}</div><button class="secondary" id="copyListing">Скопировать текст</button>`;$("copyListing").onclick=async()=>{await navigator.clipboard?.writeText(text);toast("Текст скопирован")}}
function reply(type){const t={price:"Могу немного уступить при встрече, если состояние и комплект совпадут с описанием.",condition:"Да, готов показать все дефекты при встрече. Могу дополнительно прислать фото.",delivery:"Да, могу обсудить доставку. Давайте сначала уточним способ и условия."}[type];$("replyOutput").classList.remove("hidden");$("replyOutput").innerHTML=`<div class="eyebrow">ГОТОВЫЙ ОТВЕТ</div><p style="font-size:13px;line-height:1.5;margin:8px 0">${escapeHtml(t)}</p><button class="secondary" id="copyReply">Скопировать</button>`;$("copyReply").onclick=async()=>{await navigator.clipboard?.writeText(t);toast("Ответ скопирован")}}
function calc(){const b=Number($("calcBuy").value),s=Number($("calcSell").value),fee=Number($("calcFee").value||0);if(!(b>0&&s>0)){toast("Введи цену покупки и продажи");return}const net=s*(1-fee/100)-b;const roi=b?net/b*100:0;$("calcOutput").classList.remove("hidden");$("calcOutput").innerHTML=`<div class="result-title">Расчёт</div><div class="result-price">${net.toFixed(2)} BYN</div><div class="result-meta">Ориентир после ${fee}% расходов · ROI ${roi.toFixed(1)}%</div>`}

async function buyPro(){if(state.pro){toast("Pro уже активен");return}const btn=$("buyPro");const init=tg?.initData||"";if(!init){toast("Открой FLIP внутри Telegram");return}btn.disabled=true;btn.textContent="Готовим оплату…";try{const r=await fetch(BACKEND+"/api/pro/invoice",{method:"POST",headers:{"Content-Type":"application/json","X-Flip-Init-Data":init},body:"{}"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Платёж пока не подключён на сервере");if(d.invoice_link){if(tg?.openInvoice)tg.openInvoice(d.invoice_link,(status)=>{if(status==="paid"){toast("Оплата получена");profile()}else if(status==="cancelled")toast("Оплата отменена")});else telegramOpen(d.invoice_link)}else throw new Error("Ссылка на оплату не получена")}catch(e){toast(e.message||"Не удалось открыть оплату")}finally{btn.disabled=false;updateProUI()}}

function toggleSetting(key){state.settings[key]=!state.settings[key];save();applySettings();}
function applySettings(){document.querySelectorAll(".switch[data-setting]").forEach(b=>b.classList.toggle("on",!!state.settings[b.dataset.setting]));document.documentElement.classList.toggle("reduced-motion",!state.settings.motion);document.documentElement.dataset.theme=state.settings.dark?"dark":"light";$("topTheme").textContent=state.settings.dark?"☾":"☀"}
function openSheet(type){const c=$("sheetContent");const data={about:["О FLIP","Помощник для покупок и продаж","FLIP объединяет проверку объявлений, чек-листы сделки, инструменты продавца, историю и Pro-функции."],how:["КАК РАБОТАЕТ ПРОВЕРКА","Разбор объявления","FLIP получает доступные данные объявления и сравнивает цену с рыночным ориентиром. Если данных нет, мы прямо показываем это, а не придумываем их."],trust:["БЕЗОПАСНОСТЬ","Почему можно доверять FLIP","FLIP не просит пароль Telegram, коды входа или данные банковской карты. Сервис снижает риски, но не гарантирует честность продавца или состояние товара."],privacy:["ДАННЫЕ","Как FLIP работает с данными","Telegram нужен для запуска Mini App и определения пользователя. Сервер нужен для проверки объявлений и Pro. Не отправляй в поддержку пароли, коды входа и данные банковской карты."]}[type];if(!data)return;c.innerHTML=`<span class="eyebrow">${data[0]}</span><h3>${data[1]}</h3><p>${data[2]}</p>`;$("sheet").classList.remove("hidden");closeMenu()}
function openMenu(){$("menuSheet").classList.remove("hidden");applySettings()}
function closeMenu(){$("menuSheet").classList.add("hidden")}

// navigation
document.addEventListener("click",e=>{const nav=e.target.closest("[data-nav]");if(nav){e.preventDefault();closeMenu();show(nav.dataset.nav);return}const hist=e.target.closest("[data-open-history]");if(hist){const x=state.history[Number(hist.dataset.openHistory)];if(x){show("buy");$("buyUrl").value=x.url||"";runBuy()}}const faq=e.target.closest("[data-faq]");if(faq){const id=faq.dataset.faq==="privacy"?"faqPrivacy":"faqGuarantee";$(id).classList.toggle("hidden");faq.querySelector("i").textContent=$(id).classList.contains("hidden")?"+":"−"}const info=e.target.closest("[data-info]");if(info)openSheet(info.dataset.info);if(e.target.closest("[data-close-sheet]"))$("sheet").classList.add("hidden");if(e.target.closest("[data-close-menu]"))closeMenu()});
$("runBuy").onclick=runBuy;$("clearBuy").onclick=()=>{$("buyUrl").value="";$("clearBuy").classList.add("hidden")};$("buyUrl").oninput=()=>$("clearBuy").classList.toggle("hidden",!$("buyUrl").value);$("buyUrl").onkeydown=e=>{if(e.key==="Enter")runBuy()};$("makeListing").onclick=makeListing;document.querySelectorAll("[data-reply]").forEach(b=>b.onclick=()=>reply(b.dataset.reply));$("runCalc").onclick=calc;$("buyPro").onclick=buyPro;
$("clearHistory").onclick=()=>{if(!state.history.length){toast("История уже пустая");return}state.history=[];save();renderHistory();renderRecent();toast("История очищена")};$("promoOpen").onclick=()=>$("promoBox").classList.toggle("hidden");$("promoApply").onclick=()=>{const v=$("promoInput").value.trim();$("promoMessage").textContent=v?"Промокод принят к проверке. Активация бонусов будет подключена вместе с серверной системой промокодов.":"Введи промокод"};
$("openSupport").onclick=()=>telegramOpen("https://t.me/"+SUPPORT);$("openSupportMenu").onclick=()=>telegramOpen("https://t.me/"+SUPPORT);document.querySelectorAll(".switch").forEach(b=>b.onclick=()=>toggleSetting(b.dataset.setting));$("topTheme").onclick=()=>toggleSetting("dark");$("topMenu").onclick=openMenu;
// persist deal checklist
 document.querySelectorAll("#dealChecks input").forEach((x,i)=>{const k="flipDeal"+i;x.checked=localStorage.getItem(k)==="1";x.onchange=()=>{localStorage.setItem(k,x.checked?"1":"0")}});

save();applySettings();initTelegram();setUser();renderRecent();renderHistory();updateProUI();health();profile();
